-- auto-generated by tools/supabase_seed.py — run in the BFT project SQL editor
-- source: grassroots_business  (3 rows)
insert into public.grassroots_business (bft_id, name, tier, network, stance, alliance_score, affiliation, industry, expertise, profession, platform, related, links, evidence, source, added_by, needs_verification) values
  ('gb-05629f53', 'Jacob Rothman', 'grassroots', 'bft', 'neutral', 50, NULL, NULL, NULL, NULL, 'linkedin.com/in/jacobrothman', NULL, 'linkedin.com/in/jacobrothman', 'Andy-submitted to grassroots business (w/ American Technion Society). Identity/stance not established -- verify.', 'linkedin.com/in/jacobrothman', 'Andy', 'yes'),
  ('gb-f9dbb00a', 'Nadia Schadlow', 'grassroots', 'bft', 'pro', 60, NULL, NULL, NULL, NULL, 'hudson.org', NULL, 'hudson.org', 'PRO: Hudson Institute senior fellow; former Deputy National Security Advisor for Strategy (Trump NSC). Natsec ally; added to both grassroots networks per Andy.', 'hudson.org', 'Andy', 'yes'),
  ('gb-8057cfb3', 'Anthony J. Tokarz', 'grassroots', 'bft', 'neutral', 50, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Andy-submitted to both grassroots networks. Identity/stance not established -- verify.', 'Andy-submitted', 'Andy', 'yes')
on conflict (bft_id) do nothing;
