#!/usr/bin/env python3
"""Generate Supabase seed SQL for the BFT project from the master SEED_DATA.

Extracts the grassroots_business + business_leader arrays from the standalone
HTML and emits INSERT statements (idempotent via ON CONFLICT (bft_id)).

    python3 tools/supabase_seed.py [path-to-master-html]

Writes:
    supabase/seed_bft_grassroots.sql   -> public.grassroots_business
    supabase/seed_bft_leaders.sql      -> public.business_leaders

The Jewish project is NOT auto-seeded here: religion is not inferred from names
or nationality. Populate it from a sourced/flagged list (see seed_jewish_*.sql).
"""
import os, re, sys

MASTER = sys.argv[1] if len(sys.argv) > 1 else "/Users/andy/Downloads/BFT_Living_Database_6.html"
OUT = os.path.join(os.path.dirname(__file__), "..", "supabase")

COLS = ["bft_id", "name", "tier", "network", "stance", "alliance_score", "affiliation",
        "industry", "expertise", "profession", "platform", "related", "links",
        "evidence", "source", "added_by", "needs_verification"]


def block(txt, cat):
    m = re.search(r"\n    " + re.escape(cat) + r": \[", txt)
    s = m.end()
    e = txt.find("\n    ],", s)
    return txt[s:e]


def split_records(b):
    recs, depth, ins, esc, start = [], 0, False, False, None
    for i, ch in enumerate(b):
        if ins:
            if esc: esc = False
            elif ch == "\\": esc = True
            elif ch == '"': ins = False
            continue
        if ch == '"': ins = True
        elif ch == '{':
            if depth == 0: start = i
            depth += 1
        elif ch == '}':
            depth -= 1
            if depth == 0 and start is not None:
                recs.append(b[start:i + 1]); start = None
    return recs


def fields(rec):
    d = {}
    for k, v in re.findall(r'(\w+):"((?:[^"\\]|\\.)*)"', rec):
        d[k] = re.sub(r"\\(.)", lambda m: m.group(1), v)
    return d


def q(v):
    if v is None or v == "": return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


def qi(v):
    m = re.search(r"\d+", v or "")
    return m.group(0) if m else "NULL"


def row_sql(d, tier):
    vals = {
        "bft_id": q(d.get("bftId")), "name": q(d.get("name")), "tier": q(tier), "network": q("bft"),
        "stance": q(d.get("stance")), "alliance_score": qi(d.get("allianceScore")),
        "affiliation": q(d.get("affiliation")), "industry": q(d.get("industry")),
        "expertise": q(d.get("expertise")), "profession": q(d.get("profession")),
        "platform": q(d.get("platform")), "related": q(d.get("related")), "links": q(d.get("links")),
        "evidence": q(d.get("evidence")), "source": q(d.get("source")),
        "added_by": q(d.get("addedBy")), "needs_verification": q(d.get("needsVerification")),
    }
    return "(" + ", ".join(vals[c] for c in COLS) + ")"


def emit(cat, tier, table, outfile):
    txt = open(MASTER, encoding="utf-8").read()
    recs = [fields(r) for r in split_records(block(txt, cat))]
    recs = [d for d in recs if d.get("name")]
    lines = ["-- auto-generated by tools/supabase_seed.py — run in the BFT project SQL editor",
             "-- source: %s  (%d rows)" % (cat, len(recs)),
             "insert into public.%s (%s) values" % (table, ", ".join(COLS))]
    body = [("  " + row_sql(d, tier)) for d in recs]
    sql = lines[0] + "\n" + lines[1] + "\n" + lines[2] + "\n" + ",\n".join(body) + \
          "\non conflict (bft_id) do nothing;\n"
    open(os.path.join(OUT, outfile), "w", encoding="utf-8").write(sql)
    print("wrote %s (%d rows)" % (outfile, len(recs)))
    return len(recs)


if __name__ == "__main__":
    g = emit("grassroots_business", "grassroots", "grassroots_business", "seed_bft_grassroots.sql")
    l = emit("business_leader", "leader", "business_leaders", "seed_bft_leaders.sql")
    print("BFT seed totals: %d grassroots + %d leaders = %d rows" % (g, l, g + l))
